services:

    #
    # Providers
    #
    mmoreram.controllerextra.provider.entity_provider:
        class: %mmoreram.controllerextra.provider.entity_provider.class%
        arguments:
            - "@service_container"
            - "@kernel"
            - %mmoreram.controllerextra.factory_default_method%
            - %mmoreram.controllerextra.factory_default_static%

    mmoreram.controllerextra.provider.request_parameter_provider:
        class: %mmoreram.controllerextra.provider.request_parameter_provider.class%
        arguments:
            - "@request_stack"
        calls:
            - [setRequestType, [%mmoreram.controllerextra.request%]]
