parameters:

    #
    # Resolvers
    #
    mmoreram.controllerextra.resolver.entity_annotation_resolver.class: Mmoreram\ControllerExtraBundle\Resolver\EntityAnnotationResolver

services:

    #
    # Resolvers
    #
    mmoreram.controllerextra.resolver.entity_annotation_resolver:
        class: %mmoreram.controllerextra.resolver.entity_annotation_resolver.class%
        arguments:
            - "@doctrine"
            - "@mmoreram.controllerextra.provider.entity_provider"
            - "@mmoreram.controllerextra.provider.request_parameter_provider"
            - %mmoreram.controllerextra.entity_default_name%
            - %mmoreram.controllerextra.entity_default_persist%
            - %mmoreram.controllerextra.entity_fallback_mapping%
        tags:
            - { name: controller_extra.annotation }
