parameters:

    #
    # Resolvers
    #
    mmoreram.controllerextra.resolver.form_annotation_resolver.class: Mmoreram\ControllerExtraBundle\Resolver\FormAnnotationResolver

services:

    #
    # Resolvers
    #
    mmoreram.controllerextra.resolver.form_annotation_resolver:
        class: %mmoreram.controllerextra.resolver.form_annotation_resolver.class%
        arguments:
            - "@form.registry"
            - "@form.factory"
            - %mmoreram.controllerextra.form_default_name%
        tags:
            - { name: controller_extra.annotation }
