parameters:

    #
    # Resolvers
    #
    mmoreram.controllerextra.resolver.object_manager_annotation_resolver.class: Mmoreram\ControllerExtraBundle\Resolver\ObjectManagerAnnotationResolver

services:

    #
    # Resolvers
    #
    mmoreram.controllerextra.resolver.object_manager_annotation_resolver:
        class: %mmoreram.controllerextra.resolver.object_manager_annotation_resolver.class%
        arguments:
            - "@doctrine"
            - "@mmoreram.controllerextra.provider.entity_provider"
            - %mmoreram.controllerextra.object_manager_default_name%
        tags:
            - { name: controller_extra.annotation }
